language: python
sudo: false

python:
  - 3.5
  - 3.6
  - pypy

install:
  - python -m pip install --upgrade pip coveralls
  - python -m pip install -r etc/requirements.txt

script:
  - nosetests test

branches:
  only:
    - master

